import React, { useState } from 'react';

export default function BdmsLifecycleTracker({ dispatchPayload }) {
  const [currentStage, setCurrentStage] = useState(3); // 1: Draft, 2: Validated, 3: Approved, 4: Submitted

  const stages = [
    { step: 1, label: "Draft", desc: "Generated by BANDHAN Solver" },
    { step: 2, label: "Validated", desc: "Zero Hard Constraints Violated" },
    { step: 3, label: "Approved", desc: "Sr. DEN / Dy. CPTM Sign-Off" },
    { step: 4, label: "Submitted", desc: "Dispatched to CRIS BDMS ESB" }
  ];

  return (
    <div className="bg-surface-container-lowest p-gutter-lg rounded-xl shadow-sm border border-outline-variant/30">
      <div className="flex flex-col md:flex-row md:items-center justify-between border-b border-outline-variant/40 pb-gutter-md mb-gutter-md">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="font-headline-sm text-headline-sm font-bold text-primary">BDMS Possession Approval Lifecycle</h2>
            <span className="bg-secondary text-on-secondary font-label-sm text-label-sm px-2.5 py-0.5 rounded font-bold uppercase">
              CRIS BDMS Protocol
            </span>
          </div>
          <p className="font-body-sm text-body-sm text-on-surface-variant">
            Official Block Disconnection &amp; Possession Management System (BDMS) lifecycle progression
          </p>
        </div>
      </div>

      {/* Lifecycle Progress Bar */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-gutter-md mb-gutter-lg">
        {stages.map((s) => {
          const isDone = s.step <= currentStage;
          return (
            <div
              key={s.step}
              onClick={() => setCurrentStage(s.step)}
              className={`p-4 rounded-xl border cursor-pointer transition-all ${isDone ? "bg-primary text-on-primary border-primary shadow" : "bg-surface-container-low text-on-surface border-outline-variant/30 opacity-70"}`}
            >
              <div className="flex items-center justify-between font-bold text-xs uppercase mb-1">
                <span>Stage {s.step}</span>
                {isDone && <span className="material-symbols-outlined text-sm text-secondary-fixed">check_circle</span>}
              </div>
              <div className="font-headline-sm text-title-lg font-bold">{s.label}</div>
              <p className="text-body-sm text-[11px] opacity-80 mt-1">{s.desc}</p>
            </div>
          );
        })}
      </div>

      {/* Dispatch JSON Preview */}
      {dispatchPayload && (
        <div className="bg-primary p-4 rounded-xl text-on-primary">
          <div className="flex items-center justify-between border-b border-primary-container pb-2 mb-2 font-mono text-xs">
            <span>Idempotency Key: {dispatchPayload.idempotency_key}</span>
            <span className="text-secondary-fixed font-bold uppercase">Schema: {dispatchPayload.schema_version}</span>
          </div>
          <pre className="text-xs font-mono overflow-x-auto max-h-[220px] text-on-primary-container">
            {JSON.stringify(dispatchPayload, null, 2)}
          </pre>
        </div>
      )}
    </div>
  );
}
