import React from 'react';

export default function ControlRoomOverview({ weeklyPlan, taskList, archData, onNavigate }) {
  const schedule = weeklyPlan?.schedule || [];

  return (
    <div className="space-y-gutter-lg">
      {/* 1. TODAY'S CONTROL ROOM SUMMARY */}
      <div className="bg-surface-container-lowest p-gutter-lg rounded-xl shadow-sm border border-outline-variant/30">
        <div className="flex flex-col md:flex-row md:items-center justify-between border-b border-outline-variant/30 pb-3 mb-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="w-3 h-3 rounded-full bg-on-tertiary-container animate-pulse"></span>
              <h2 className="font-headline-sm text-headline-sm font-bold text-primary">
                Today's Control Room Operations — {new Date().toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'short', day: 'numeric' })}
              </h2>
            </div>
            <p className="text-body-sm text-on-surface-variant">
              Central Control Desk • Northern Railway (NR / DLI Division) • High-Density Corridor HDN-1
            </p>
          </div>
          <div className="flex items-center gap-2 mt-2 md:mt-0">
            <span className="bg-primary text-on-primary text-label-sm px-3 py-1 rounded font-bold uppercase">
              18 HQs Synchronized
            </span>
            <span className="bg-on-tertiary-container/10 text-on-tertiary-container text-label-sm font-bold px-3 py-1 rounded">
              Kavach 4.0 Active
            </span>
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-gutter-md">
          <div className="bg-surface-container-low p-3 rounded-lg border border-primary/20">
            <span className="text-label-sm text-outline uppercase font-bold">Today's Active Blocks</span>
            <div className="font-display-lg text-display-lg font-black text-primary my-1">
              {schedule.length || 14}
            </div>
            <span className="text-[11px] text-on-tertiary-container font-bold">100% Traffic Interlocked</span>
          </div>
          <div className="bg-surface-container-low p-3 rounded-lg border border-secondary/20">
            <span className="text-label-sm text-outline uppercase font-bold">Corridor Retention Rate</span>
            <div className="font-display-lg text-display-lg font-black text-secondary my-1">
              {weeklyPlan?.kpis?.asset_availability_pct || 97.8}%
            </div>
            <span className="text-[11px] text-on-surface-variant font-medium">NDLS-GZB Corridor</span>
          </div>
          <div className="bg-surface-container-low p-3 rounded-lg border border-tertiary-container/20">
            <span className="text-label-sm text-outline uppercase font-bold">Possession Hours Saved</span>
            <div className="font-display-lg text-display-lg font-black text-tertiary-container my-1">
              {archData?.multi_department_shadows?.total_hours_saved || 142.5}h
            </div>
            <span className="text-[11px] text-on-tertiary-container font-bold">Budai-Dekker Grouping</span>
          </div>
          <div className="bg-surface-container-low p-3 rounded-lg border border-error/20">
            <span className="text-label-sm text-outline uppercase font-bold">Active USFD Alerts</span>
            <div className="font-display-lg text-display-lg font-black text-error my-1">3</div>
            <span className="text-[11px] text-error font-bold">Zero Unattended &gt;24h</span>
          </div>
        </div>
      </div>

      {/* 2. RECOMMENDED OPTIMIZED BLOCKS */}
      <div className="bg-surface-container-lowest p-gutter-lg rounded-xl shadow-sm border border-outline-variant/30">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="font-headline-sm text-headline-sm font-bold text-primary">Recommended Optimized Block Possessions</h3>
            <p className="text-body-sm text-on-surface-variant">AI-prioritized block windows generated by BANDHAN CP-SAT/ALNS solver</p>
          </div>
          <button
            onClick={() => onNavigate && onNavigate("explainable")}
            className="bg-primary text-on-primary text-label-sm font-bold px-3 py-1.5 rounded uppercase hover:bg-primary-container shadow-xs"
          >
            Inspect AI Decision Trail
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-gutter-md">
          {schedule.slice(0, 3).map((item, idx) => (
            <div key={idx} className="bg-surface-container-low p-4 rounded-xl border border-outline-variant/30 flex flex-col justify-between">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="font-title-lg text-title-lg font-bold text-primary">{item.task_id || `BLK_${idx+1}`}</span>
                  <span className="bg-secondary text-on-secondary text-xs px-2 py-0.5 rounded font-bold uppercase">{item.department}</span>
                </div>
                <div className="text-body-sm text-on-surface font-semibold">Section: {item.section_id}</div>
                <div className="text-body-sm text-on-surface-variant mt-1">Window: {String(item.start_time).substring(11, 16)} - {String(item.end_time).substring(11, 16)}</div>
              </div>
              <div className="mt-3 pt-2 border-t border-outline-variant/30 flex items-center justify-between text-label-sm">
                <span className="text-on-tertiary-container font-bold">DRI Priority: {item.priority_score?.toFixed(2) || "8.45"}</span>
                <span className="text-outline">Gap-Fit: {item.gap_fit_score?.toFixed(2) || "0.89"}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 3. TRAIN CIRCULATION IMPACT */}
      <div className="bg-surface-container-lowest p-gutter-lg rounded-xl shadow-sm border border-outline-variant/30">
        <h3 className="font-headline-sm text-headline-sm font-bold text-primary mb-2">Train Circulation &amp; Timetable Impact</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-gutter-md font-body-sm">
          <div className="bg-surface-container-low p-3 rounded-lg border border-outline-variant/30">
            <span className="font-bold text-primary block">12301 Rajdhani Express</span>
            <span className="text-on-surface-variant">Diverted via 3rd Suburban Line • Zero Detention</span>
          </div>
          <div className="bg-surface-container-low p-3 rounded-lg border border-outline-variant/30">
            <span className="font-bold text-primary block">12951 Tejas Rajdhani</span>
            <span className="text-on-surface-variant">Handled on Up Slow Line • Kavach TSR 45 Clamped</span>
          </div>
          <div className="bg-surface-container-low p-3 rounded-lg border border-outline-variant/30">
            <span className="font-bold text-primary block">BOXN Coal Rakes (Freight)</span>
            <span className="text-on-surface-variant">Slotted into natural freight lull (02:00 - 05:00 IST)</span>
          </div>
        </div>
      </div>

      {/* 4. CRITICAL TRACK DEFECTS */}
      <div className="bg-surface-container-lowest p-gutter-lg rounded-xl shadow-sm border border-error/20">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-error text-2xl">warning</span>
            <h3 className="font-headline-sm text-headline-sm font-bold text-primary">Critical Track Flaw Alerts (USFD/IMR)</h3>
          </div>
          <span className="bg-error-container text-on-error-container font-label-sm text-label-sm px-2.5 py-1 rounded font-bold uppercase">3 Urgent Actions</span>
        </div>
        <div className="space-y-2 font-body-sm">
          <div className="bg-surface-container-low p-3 rounded-lg flex items-center justify-between border border-outline-variant/30">
            <div>
              <span className="font-bold text-primary block">[NR/DLI] KM 124/8-10 Dn Line (Ghaziabad-Khurja)</span>
              <span className="text-on-surface-variant">Internal Transverse Fatigue Defect (IMR-W). Clamped at 30 KMPH.</span>
            </div>
            <span className="bg-error text-on-error px-2.5 py-1 rounded text-label-sm font-bold uppercase">Gang 04 Dispatched</span>
          </div>
        </div>
      </div>

      {/* 5. KPI SUMMARY & 6. ALERTS */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-gutter-lg">
        <div className="bg-surface-container-lowest p-gutter-lg rounded-xl shadow-sm border border-outline-variant/30">
          <h3 className="font-headline-sm text-headline-sm font-bold text-primary mb-2">Operational KPIs Summary</h3>
          <div className="space-y-2 text-body-sm font-body-sm">
            <div className="flex justify-between p-2 bg-surface-container-low rounded">
              <span className="font-medium text-on-surface">Asset Availability</span>
              <span className="font-bold text-on-tertiary-container">{weeklyPlan?.kpis?.asset_availability_pct || 97.8}%</span>
            </div>
            <div className="flex justify-between p-2 bg-surface-container-low rounded">
              <span className="font-medium text-on-surface">Train Circulation Delays</span>
              <span className="font-bold text-primary">{weeklyPlan?.kpis?.est_delay_minutes || 38.5} Mins</span>
            </div>
            <div className="flex justify-between p-2 bg-surface-container-low rounded">
              <span className="font-medium text-on-surface">Possessions Consolidated</span>
              <span className="font-bold text-secondary">{archData?.multi_department_shadows?.possessions_saved || 28} Mega-Blocks</span>
            </div>
          </div>
        </div>

        <div className="bg-surface-container-lowest p-gutter-lg rounded-xl shadow-sm border border-outline-variant/30">
          <h3 className="font-headline-sm text-headline-sm font-bold text-primary mb-2">Control Room Conflict &amp; Safety Alerts</h3>
          <div className="space-y-2 text-body-sm font-body-sm">
            <div className="p-2.5 bg-on-tertiary-container/10 text-on-tertiary-container rounded font-bold flex items-center gap-2">
              <span className="material-symbols-outlined text-sm">check_circle</span>
              <span>Zero Train Occupation Overlaps</span>
            </div>
            <div className="p-2.5 bg-primary-container/10 text-primary rounded font-bold flex items-center gap-2">
              <span className="material-symbols-outlined text-sm">lock</span>
              <span>24h Execution Freeze Lock Engaged</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
