import React from 'react';

function Metric({ label, value, detail }) {
  return (
    <div className="bg-surface-container-lowest border border-outline-variant/30 rounded-lg p-4">
      <div className="text-label-sm uppercase tracking-wide text-on-surface-variant">{label}</div>
      <div className="text-headline-sm font-bold text-primary mt-1">{value}</div>
      {detail && <div className="text-body-sm text-on-surface-variant mt-1">{detail}</div>}
    </div>
  );
}

function metricValue(value, suffix = '') {
  return value === undefined || value === null ? 'Unavailable' : `${value}${suffix}`;
}

export default function MlEvidencePanel({ evidence, demand }) {
  if (!evidence) return <div className="p-6 bg-surface-container-low rounded-xl" role="status">ML evidence did not load. Check the dashboard endpoint error above and use Refresh Feeds to retry. The scheduler may still be available for other features.</div>;
  const metrics = evidence.metrics || {};
  const m1 = metrics.m1_audit || {};
  const m2 = metrics.m2_metrics || {};
  const m4 = metrics.m4_delay_metrics || {};
  const m5 = metrics.m5_metrics || {};
  const m6 = metrics.m6_metrics || {};
  const benchmark = metrics.benchmark_status || {};
  return (
    <section className="space-y-6">
      <div className="bg-primary text-on-primary rounded-xl p-6">
        <div className="text-label-sm uppercase tracking-widest opacity-80">Evidence status</div>
        <h2 className="text-headline-md font-bold mt-1">Synthetic, reproducible, auditable</h2>
        <p className="text-body-sm mt-2 opacity-90">Every number below is generated by the repository pipeline. Operational deployment requires railway movement and maintenance validation.</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Metric label="M1 grouped PR-AUC" value={m1.pr_auc?.grouped_leakage_safe == null ? 'Unavailable' : metricValue(Number(m1.pr_auc.grouped_leakage_safe).toFixed(3))} detail="Synthetic asset-grouped audit; not field accuracy" />
        <Metric label="M2 CQR coverage" value={m2.cqr_interval_coverage == null ? 'Unavailable' : metricValue(Number(m2.cqr_interval_coverage).toFixed(2), '%')} detail="Synthetic interval evaluation" />
        <Metric label="M5 C-index" value={m5.c_index == null ? 'Unavailable' : metricValue(Number(m5.c_index).toFixed(3))} detail="Synthetic survival evaluation" />
        <Metric label="M6 p90 coverage" value={m6.p90_coverage == null ? 'Unavailable' : metricValue((Number(m6.p90_coverage) * 100).toFixed(2), '%')} detail="Synthetic hourly goods forecast" />
        <Metric label="M4 delay MAE" value={m4.mae_minutes == null ? 'Unavailable' : metricValue(Number(m4.mae_minutes).toFixed(3), ' min')} detail="Synthetic simulator-labelled candidates" />
        <Metric label="Benchmark scenarios" value={benchmark.scenario_count == null ? 'Unavailable' : benchmark.scenario_count} detail="Seeded synthetic runs" />
      </div>
      <div className={`rounded-xl p-5 border ${evidence.plan_verification?.valid ? 'bg-tertiary-container border-tertiary' : 'bg-error-container border-error'}`}>
        <div className="font-bold">Independent safety verifier</div>
        <div className="text-body-sm mt-1">{evidence.plan_verification?.valid ? 'Current plan passed verification with zero reported violations.' : 'Verification is unavailable until a plan is generated.'}</div>
      </div>
      <div className="bg-surface-container-low rounded-xl p-5 border border-outline-variant/30">
        <div className="font-bold text-primary">Predictive block demand</div>
        <div className="text-body-sm text-on-surface-variant mt-1">M5 flags assets likely to fail within 30 days, including assets without an open defect record.</div>
        <div className="text-headline-sm font-bold mt-2">{demand?.items ? `${demand.items.filter((item) => item.recommended_block_demand).length} candidate blocks` : 'Demand evidence unavailable'}</div>
      </div>
    </section>
  );
}